import { lazy, Suspense, useEffect } from 'react';
import { Navigate, Route, Routes, useLocation, useSearchParams } from 'react-router-dom';
import { ArchiveX, LoaderCircle } from 'lucide-react';
import { AnimatePresence } from 'framer-motion';
import { Shell } from './components/Shell';
import { Button } from './components/ui';
import { ErrorBoundary } from './components/ErrorBoundary';
import { useAuth } from './lib/auth';

const Landing=lazy(()=>import('./pages/Landing'));const PublicProfile=lazy(()=>import('./pages/PublicProfile'));const Dashboard=lazy(()=>import('./pages/Dashboard'));const Editors=lazy(()=>import('./pages/Editors'));const Onboarding=lazy(()=>import('./pages/Onboarding'));
function Loading(){return <div className="grid min-h-[60vh] place-items-center" role="status"><LoaderCircle className="animate-spin text-cyan-300"/><span className="sr-only">Loading route</span></div>}
function Protected({children}:{children:React.ReactNode}){const auth=useAuth(),location=useLocation();if(auth.isLoading)return <Loading/>;if(!auth.isAuthenticated)return <div className="container-shell grid min-h-[70vh] place-items-center text-center"><div><div className="eyebrow justify-center">Private collection</div><h1 className="mt-5 text-5xl font-bold">Curator access required.</h1><p className="muted mt-4">Sign in with Auth0 to enter your studio. Server permissions protect every write.</p><Button className="btn-primary mt-7" onClick={()=>auth.login(location.pathname)}>Continue securely</Button></div></div>;return children}
function NotFound(){return <div className="container-shell grid min-h-[70vh] place-items-center text-center"><div><ArchiveX className="mx-auto text-violet-300" size={42}/><div className="eyebrow mt-7 justify-center">404 · Lost sector</div><h1 className="mt-5 text-[clamp(3rem,9vw,6rem)] font-bold leading-none tracking-[-.05em]">No save<br/><span className="text-gradient">exists here.</span></h1><p className="muted mt-3">Return to the archive before the signal fades.</p><a className="btn btn-primary mt-7" href="/">Return home</a></div></div>}
function ScrollToTop(){const {pathname}=useLocation();useEffect(()=>{if(!window.location.hash)window.scrollTo({top:0,left:0,behavior:'instant' as ScrollBehavior})},[pathname]);return null}
function AuthCallback(){const [params]=useSearchParams();const error=params.get('error');const description=params.get('error_description');if(error)return <div className="container-shell grid min-h-[70vh] place-items-center text-center"><div role="alert"><div className="eyebrow justify-center">Sign-in interrupted</div><h1 className="mt-5 text-4xl font-bold">The gate did not open.</h1><p className="muted mx-auto mt-4 max-w-md">{description||'The sign-in flow was cancelled or expired. Return home and try again.'}</p><a className="btn btn-primary mt-7" href="/">Return home</a></div></div>;return <Loading/>}
export default function App(){const location=useLocation();return <ErrorBoundary><div className="grain"><Suspense fallback={<Loading/>}><ScrollToTop/><AnimatePresence mode="wait" initial={false}><Routes location={location} key={location.pathname}><Route element={<Shell/>}><Route index element={<Landing/>}/><Route path="u/:handle" element={<PublicProfile/>}/><Route path="demo" element={<Navigate to="/u/nova" replace/>}/><Route path="onboarding" element={<Onboarding/>}/><Route path="dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="dashboard/:editor" element={<Protected><Editors/></Protected>}/><Route path="auth/callback" element={<AuthCallback/>}/><Route path="*" element={<NotFound/>}/></Route></Routes></AnimatePresence></Suspense></div></ErrorBoundary>}
