import { Archive, ChevronRight, LogIn, Menu, X } from 'lucide-react';
import { useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { isDemoMode } from '../lib/api';
import { useAuth } from '../lib/auth';
import { Button, ThemeToggle } from './ui';

export function Shell() {
  const [open, setOpen] = useState(false); const auth = useAuth(); const location = useLocation();
  const links = location.pathname.startsWith('/u/') ? [['Rig','#rig'],['Hall of Fame','#featured'],['Chronicle','#chronicle'],['AI Guide','#guide']] : [['Showcase','/u/nova'],['Dashboard','/dashboard']];
  return <><a href="#main" className="skip-link">Skip to content</a><header className="sticky top-0 z-50 border-b border-white/10 bg-canvas/75 backdrop-blur-xl"><div className="container-shell flex h-[72px] items-center gap-4"><Link to="/" className="flex min-h-11 items-center gap-2.5 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-300/25 bg-cyan-300/10 text-cyan-300"><Archive size={19}/></span><span>Save<span className="text-gradient">Point</span></span></Link>{isDemoMode && <span className="hidden rounded-full border border-violet-400/30 bg-violet-400/10 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.16em] text-violet-300 sm:inline">Safe demo</span>}<nav className="ml-auto hidden items-center gap-1 md:flex" aria-label="Primary">{links.map(([label,to]) => to.startsWith('#') ? <a className="btn border-0 bg-transparent text-sm" key={to} href={to}>{label}</a> : <NavLink className="btn border-0 bg-transparent text-sm" key={to} to={to}>{label}</NavLink>)}</nav><div className="ml-auto flex gap-2 md:ml-2"><ThemeToggle/>{auth.isAuthenticated ? <Link className="btn hidden sm:inline-flex" to="/dashboard">Studio <ChevronRight size={16}/></Link> : <Button className="hidden sm:inline-flex" onClick={() => auth.login()}><LogIn size={16}/> Sign in</Button>}<Button className="icon-btn md:hidden" aria-label="Open navigation" onClick={() => setOpen(true)}><Menu size={20}/></Button></div></div></header><AnimatePresence>{open && <motion.div className="fixed inset-0 z-[70] bg-canvas/95 p-5 backdrop-blur-2xl md:hidden" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="flex justify-end"><Button className="icon-btn" aria-label="Close navigation" onClick={() => setOpen(false)}><X/></Button></div><nav className="mt-12 grid gap-3" aria-label="Mobile">{links.map(([label,to]) => <Link className="flex min-h-14 items-center justify-between border-b border-white/10 text-2xl" key={to} to={to} onClick={() => setOpen(false)}>{label}<ChevronRight/></Link>)}</nav></motion.div>}</AnimatePresence><main id="main"><Outlet/></main><footer className="container-shell flex flex-col gap-4 border-t border-white/10 py-10 text-sm text-ink/60 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} SavePoint Archive</span><span className="font-mono text-xs">BUILT FOR THE GAMES THAT STAY</span></footer></>;
}
